'use client';

import type { ComponentProps } from 'react';
import type { SmartTrader } from './smart-trader';
import { useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';

type Props = ComponentProps<typeof SmartTrader>;

export function OneStop({ activeSymbol, currentTick, digitStats, selectedDigit = 5, setSelectedDigit, activeAccount, isConnected, isBuying, onRun, stake, setStake }: Props) {
  const [contract, setContract] = useState('Over/Under');
  const [direction, setDirection] = useState('Auto (Smart)');
  const digits = digitStats?.percentages?.length === 10 ? digitStats.percentages : Array(10).fill(10);
  const price = currentTick?.quote ?? currentTick?.ask;
  const top = useMemo(() => digits.map((value, digit) => ({ digit, value })).sort((a, b) => b.value - a.value).slice(0, 3), [digits]);
  const format = (value: number) => `${value.toFixed(1)}%`;
  const market = activeSymbol?.underlying_symbol_name ?? activeSymbol?.underlying_symbol ?? 'Volatility 100 Index';
  return <main className="min-h-[calc(100dvh-76px)] overflow-x-auto bg-[#0f0f19] p-3 text-[#f1f0f5] sm:p-5"><div className="mx-auto min-w-[980px] max-w-[1680px] space-y-3">
    <header className="border-b border-[#3d3a42] pb-3 text-center"><h1 className="text-lg font-black tracking-wide text-[#d4af37]">CROWN LAST DIGIT PREDICTION CROWN</h1><p className="text-[9px] uppercase tracking-[.35em] text-[#00c390]">Real-time AI analysis</p><div className="mt-2 flex justify-center gap-6 text-[9px] text-[#9c9aae]"><span className="text-[#00c390]">● LIVE / CURRENT DIGIT</span><span>● HIGHEST %</span><span>● 2ND HIGHEST %</span><span>● LOWEST %</span></div></header>
    <div className="grid grid-cols-[minmax(270px,1fr)_minmax(430px,1.75fr)_minmax(270px,1fr)] gap-3">
      <section className="space-y-3"><Panel title="VOLATILITY INDEX"><div className="rounded border border-[#514926] bg-[#1b1a29] p-3"><div className="text-[9px] text-[#9b98aa]">MARKET</div><b>{market}</b><div className="mt-3 border-t border-[#514926] pt-2 text-[9px] text-[#9b98aa]">INDEX PRICE</div><strong className="block text-xl text-[#d4af37]">{price ? Number(price).toFixed(2) : '—'}</strong></div></Panel><Panel title="LIVE PRICE"><div className="py-5 text-center text-3xl font-black">{price ? Number(price).toFixed(2) : '—'}<div className="mt-1 text-[9px] text-[#d4af37]">{market}</div></div></Panel><Panel title="INCOMING TICK"><div className="mx-auto grid size-16 place-items-center rounded-full border border-[#d4af37] text-2xl font-black text-[#d4af37]">{price ? String(Math.floor(Number(price) * 10) % 10) : '—'}</div></Panel><Panel title="LIVE DIGIT TRACKER"><div className="flex items-center justify-between text-[9px] text-[#aaa7ba]"><span>CURRENT</span><span>TARGET</span><span>REMAINING</span></div><div className="mt-3 flex justify-around text-lg text-[#00c390]"><b>{price ? String(Math.floor(Number(price) * 10) % 10) : '—'}</b><span>→</span><b>{selectedDigit}</b></div></Panel></section>
      <section className="space-y-3"><Panel title="DIGIT 0 TO 4"><DigitRow digits={digits.slice(0,5)} selectedDigit={selectedDigit} setSelectedDigit={setSelectedDigit} /><div className="mt-3 grid grid-cols-2 gap-2"><Metric title="OVER (≥5)" value={format(digits.slice(5).reduce((a,b)=>a+b,0))} /><Metric title="UNDER (≤4)" value={format(digits.slice(0,5).reduce((a,b)=>a+b,0))} /></div><div className="mt-2 flex justify-between rounded border border-[#514926] p-2 text-[10px]"><span>THRESHOLD</span><b className="text-[#d4af37]">{format(Math.max(...digits))}</b></div></Panel><Panel title="AI ENGINE UNDER 0 - 4"><div className="grid grid-cols-5 gap-2 text-center text-[9px]">{['AI SCANNING','CURSOR TOUCHING','CONFIRMATION CHECK','EXECUTION POINT','TRADE EXECUTED'].map((x,i)=><div key={x}><div className="mx-auto mb-1 grid size-7 place-items-center rounded-full border border-[#00c390] text-[#00c390]">{i+1}</div><span>{x}</span></div>)}</div><div className="mt-3 grid grid-cols-5 gap-1 text-center text-[9px]">{['ENTRY POINT','LIVE CURSOR','CONFIRMATION','TRADE STATUS','CONFIDENCE'].map((x,i)=><div className="border border-[#155f61] bg-[#14252d] p-2" key={x}><span>{x}</span><b className="block text-[#00c390]">{i===0?selectedDigit:i===4?'84.4%':i===3?(isBuying?'Executing':'Executing'):'✓'}</b></div>)}</div></Panel><Panel title="DIGIT STRENGTH RANKING"><div className="flex h-24 items-end gap-2">{digits.map((v,d)=><div className="flex flex-1 flex-col items-center gap-1" key={d}><span className="text-[8px]">{format(v)}</span><div className={`w-full rounded-t ${d===selectedDigit?'bg-[#f27670]':'bg-[#00c390]'}`} style={{height:`${Math.max(12,v*5)}%`}} /><span className="text-[9px]">{d}</span></div>)}</div></Panel></section>
      <section className="space-y-3"><Panel title="KEY DIGITS">{top.map((x,i)=><div className="mb-2 flex items-center justify-between rounded border border-[#514926] bg-[#1b1a29] p-2 text-xs" key={x.digit}><b className={i===0?'text-[#00c390]':i===1?'text-[#d4af37]':'text-[#f27670]'}>{x.digit}</b><span>{i===0?'HIGHEST':i===1?'2ND HIGHEST':'LOWEST'}<b className="ml-3">{format(x.value)}</b></span></div>)}</Panel><Panel title="SIGNAL (TOP 3 DIGITS)">{top.map(x=><div className="mb-2 rounded border border-[#155f61] p-2 text-[#00c390]" key={x.digit}>DIGIT {x.digit} <b className="float-right">TOP</b></div>)}</Panel><Panel title="TOTAL % OVER AND UNDER"><div className="flex justify-between text-xs"><b className="text-[#00c390]">UNDER 59.4%</b><b className="text-[#d4af37]">OVER 40.6%</b></div><div className="mt-3 flex h-2"><div className="w-3/5 bg-[#00c390]" /><div className="w-2/5 bg-[#d4af37]" /></div></Panel><Panel title="AI ENDPOINT (TRADE SIGNAL)"><div className="rounded border border-[#00c390] bg-[#14252d] p-3"><div className="text-[9px]">UNDER DIGIT {selectedDigit}</div><strong className="text-xl text-[#00c390]">AI ENDPOINT: {selectedDigit}</strong><div className="mt-3 text-[10px]">STRONGEST <b className="float-right">{format(Math.max(...digits))}</b></div></div></Panel></section>
    </div>
    <section className="mx-auto max-w-[480px] rounded-xl border border-[#514926] bg-[#191827] p-3"><div className="flex rounded-full bg-[#322f4a] text-center text-[10px]"><button type="button" onClick={()=>setContract('Matches')} className={`flex-1 rounded-full py-2 ${contract==='Matches'?'bg-[#0f0f19] text-[#d4af37]':''}`}>Matches</button><button type="button" onClick={()=>setContract('Differs')} className={`flex-1 rounded-full py-2 ${contract==='Differs'?'bg-[#0f0f19] text-[#d4af37]':''}`}>Differs</button></div><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-[9px]">STAKE<input value={stake} onChange={e=>setStake(e.target.value)} className="mt-1 w-full rounded border border-[#514926] bg-transparent p-2 text-sm" /></label><label className="text-[9px]">DURATION<input defaultValue="5" className="mt-1 w-full rounded border border-[#514926] bg-transparent p-2 text-sm" /></label></div><div className="mt-2 rounded border border-[#514926] p-2 text-xs">Prediction <b className="float-right">Last digit of the price will {contract.toLowerCase()} {selectedDigit}</b></div><Button onClick={onRun} disabled={!isConnected || isBuying} className="mt-3 w-full bg-[#d4af37] text-[#0f0f19] hover:bg-[#e6c65c]">Buy @ {stake || '10.00'} USD</Button></section>
  </div></main>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-lg border border-[#514926] bg-[#1d1c2c] p-3 shadow-lg"><h2 className="mb-3 text-[10px] font-black tracking-wide text-[#f0d06a]">{title}</h2>{children}</div>}
function Metric({title,value}:{title:string;value:string}){return <div className="rounded border border-[#155f61] bg-[#14252d] p-2 text-center"><div className="text-[8px] text-[#aaa7ba]">{title}</div><b className="text-sm text-[#00c390]">{value}</b></div>}
function DigitRow({digits,selectedDigit,setSelectedDigit}:{digits:number[];selectedDigit:number;setSelectedDigit?: (d:number)=>void}){return <div className="grid grid-cols-5 gap-2">{digits.map((v,d)=><button type="button" key={d} onClick={()=>setSelectedDigit?.(d)} className={`rounded border p-2 text-center ${d===selectedDigit?'border-[#f27670] bg-[#3b2938]':'border-[#3c3b51] bg-[#242333]'}`}><span className="block text-[9px] text-[#00c390]">{v.toFixed(1)}%</span><span className="mt-2 block h-5 rounded bg-[#4fc594]" /><b className="text-xs">{d}</b></button>)}</div>}
export default OneStop;
