import React from 'react';

export const FooterNav: React.FC = () => {
  const items = [
    '🎯 FOCUS',
    '🧭 PLAN',
    '▶ EXECUTE',
    '🧠 PREDICT',
    '📈 TRADE',
    '🪙 PROFIT',
    '🛡 DISCIPLINE',
    '♥ PATIENCE',
    '♛ SUCCESS',
  ];

  return (
    <footer className="mt-8">
      <nav className="flex flex-wrap items-center justify-between gap-2 pt-3.5 pb-2 border-t border-[rgba(212,175,55,0.35)] font-sans font-bold text-[11px] tracking-wider text-[#8b8b8b] uppercase">
        {items.map((item, idx) => (
          <div key={idx} className="flex items-center gap-1.5 hover:text-[#F4CB4B] transition-colors cursor-default">
            {item}
          </div>
        ))}
      </nav>

      <div className="text-center font-mono text-[10px] text-[#8b8b8b] mt-3 leading-relaxed max-w-4xl mx-auto">
        Digit percentages and signals are generated by real-time Deriv WebSocket feed tick sample distribution analysis. This application is for educational and analytical purposes. Financial trading involves substantial risk of loss — trade responsibly.
      </div>
    </footer>
  );
};
